import cx_Oracle
import csv
import os
from pathlib import Path
import requests
from datetime import datetime
import threading
import time
import pandas as pd
import subprocess


oracle_client = "C:\instantclient_19_5"
os.environ["ORACLE_HOME"] = oracle_client
os.environ["PATH"] = oracle_client+os.pathsep+os.environ["PATH"]
os.environ["NLS_LANG"] = "AMERICAN_AMERICA.TH8TISASCII"


def QC_PASS():
  my_dsn = cx_Oracle.makedsn("172.16.6.82", port=1521, sid="NYTG")
  conn = cx_Oracle.connect(user="nyg1", password="nyg1",
                           dsn=my_dsn, encoding="UTF-8", nencoding="UTF-8")
  cursor = conn.cursor()
  print("START_RUN")
  sql = """ SELECT BU,MC_LINE,SEW_DATE, SO_NO, SO_YEAR,SAM,SCROE, SEW_QTY
FROM (
SELECT 'NYG1' BU,MC_LINE, TRUNC(S1.WAIT_DATE) SEW_DATE, S1.SO_NO, S1.SO_YEAR,GET_SAM_SCORE_SO('SAM',SO_NO,SO_YEAR) SAM,GET_SAM_SCORE_SO('SCROE',SO_NO,SO_YEAR) SCROE, SUM(S1.QTY) SEW_QTY
FROM VB_SEW_WAITFN_LINE_V1 S1
WHERE SO_YEAR >= TO_CHAR(SYSDATE,'YY')-1
GROUP BY  MC_LINE,TRUNC(S1.WAIT_DATE), S1.SO_NO, S1.SO_YEAR
UNION ALL
SELECT 'NYG2' BU, MC_LINE,TRUNC(S2.WAIT_DATE) SEW_DATE, S2.SO_NO, S2.SO_YEAR,GET_SAM_SCORE_SO('SAM',SO_NO,SO_YEAR) SAM,GET_SAM_SCORE_SO('SCROE',SO_NO,SO_YEAR) SCROE, SUM(S2.QTY) SEW_QTY
FROM NYG_PHO.VB_SEW_WAITFN_LINE_V1@NYG2.WORLD S2
WHERE SO_YEAR >= TO_CHAR(SYSDATE,'YY')-1
GROUP BY MC_LINE, TRUNC(S2.WAIT_DATE), S2.SO_NO, S2.SO_YEAR
UNION ALL
SELECT 'NYG3' BU,MC_LINE, TRUNC(S3.WAIT_DATE) SEW_DATE, S3.SO_NO, S3.SO_YEAR,GET_SAM_SCORE_SO('SAM',SO_NO,SO_YEAR) SAM,GET_SAM_SCORE_SO('SCROE',SO_NO,SO_YEAR) SCROE, SUM(S3.QTY) SEW_QTY
FROM NYG3.VB_SEW_WAITFN_LINE_V1 S3
WHERE SO_YEAR >= TO_CHAR(SYSDATE,'YY')-1
GROUP BY MC_LINE, TRUNC(S3.WAIT_DATE), S3.SO_NO, S3.SO_YEAR
UNION ALL
SELECT 'NYG4' BU,MC_LINE, TRUNC(S4.WAIT_DATE) SEW_DATE, S4.SO_NO, S4.SO_YEAR,GET_SAM_SCORE_SO('SAM',SO_NO,SO_YEAR) SAM,GET_SAM_SCORE_SO('SCROE',SO_NO,SO_YEAR) SCROE, SUM(S4.QTY) SEW_QTY
FROM NYG4.VB_SEW_WAITFN_LINE_V1@NYG4.WORLD S4
WHERE SO_YEAR >= TO_CHAR(SYSDATE,'YY')-1
GROUP BY  MC_LINE,TRUNC(S4.WAIT_DATE), S4.SO_NO, S4.SO_YEAR
UNION ALL
SELECT 'NYG5' BU,MC_LINE, TRUNC(S4.WAIT_DATE) SEW_DATE, S4.SO_NO, S4.SO_YEAR,NYG1.GET_SAM_SCORE_SO@NYG5.WORLD('SAM',SO_NO,SO_YEAR) SAM,NYG1.GET_SAM_SCORE_SO@NYG5.WORLD('SCROE',SO_NO,SO_YEAR) SCROE, SUM(S4.QTY) SEW_QTY
FROM NYG1.VB_SEW_WAITFN_LINE_V1@NYG5.WORLD S4
WHERE SO_YEAR >= TO_CHAR(SYSDATE,'YY')-1
GROUP BY  MC_LINE,TRUNC(S4.WAIT_DATE), S4.SO_NO, S4.SO_YEAR
UNION ALL
SELECT 'NYG6' BU,MC_LINE, TRUNC(S4.WAIT_DATE) SEW_DATE, S4.SO_NO, S4.SO_YEAR,NYG1.GET_SAM_SCORE_SO@NYG6.WORLD('SAM',SO_NO,SO_YEAR) SAM,NYG1.GET_SAM_SCORE_SO@NYG6.WORLD('SCROE',SO_NO,SO_YEAR) SCROE, SUM(S4.QTY) SEW_QTY
FROM NYG1.VB_SEW_WAITFN_LINE_V1@NYG6.WORLD S4
WHERE SO_YEAR >= TO_CHAR(SYSDATE,'YY')-1
GROUP BY  MC_LINE,TRUNC(S4.WAIT_DATE), S4.SO_NO, S4.SO_YEAR) M
"""

  df = pd.read_sql_query(sql, conn)
  print(df.sample(n=2))

  df.to_excel(r'C:\QVD_DATA\COM_GARMENT\NYG\QC_PASS.xlsx', index=False)


QC_PASS()

